baseUrl = "/educacion-latam/"
title = "Educación Latam"
theme = "hugo-titi"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
publishDir = "../docs/educacion-latam"

[menu]
  [[menu.burger]]
    name = "Inicio"
    url = "/"
    weight = 1

[params]
  # SEO general site description
  description = "Site SEO description"

  [params.nav]
    bg = "#ffffff"
    color = "#105EAD"
    logo = "images/logo-bid.png"
    logoWidth = "150px"
    # Optional, true by default
    # fixed = true

  [[params.social]]
    icon = "twitter"
    url = "https://twitter.com/datasketch"
  [[params.social]]
    icon = "facebook"
    url = "https://www.facebook.com/datasketch/"
  [[params.social]]
    icon = "instagram"
    url = "https://www.instagram.com/datasketch/"

  [params.footer]
    text = "La división de Educación del Banco Interamericano de Desarrollo convocó en 2018 a líderes de opinión de más de 16 países de América Latina y el Caribe al Curso Movilizando Políticas Educativas Efectivas. Periodistas, Rectores de Universidades, filántropos y activistas sociales trabajaron juntos durante 8 semanas y en esta edición usted podrá acercarse a la realidad y prioridades que ellos identificaron para la región"
    bg = "black"
    color = "white"
