baseURL = "/via-lactea/"
languageCode = "es-co"
title = "Vía láctea"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
publishDir = "../docs/via-lactea/"
theme = "milky-way"
hrefTargetBlank = true
# googleAnalytics = "UA-110184023-1"

[menu]
  [[menu.main]]
    url = "https://twitter.com/datasketch"
    name = "twitter"
    weight = 3
  [[menu.main]]
    url = "https://www.instagram.com/datasketch/"
    name = "instagram"
    weight = 1
  [[menu.main]]
    url = "https://www.facebook.com/datasketch"
    name = "facebook-f"
    weight = 2