baseURL = "/lideres-sociales/"
title = "Especiales Datasketch"
theme = "hugo-titi"
publishDir = "../docs/lideres-sociales"
disqusShortname = "datasketch"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  css = ['custom.css']
  [params.nav]
    bg = "#2a2a2a"
    color = "#ffffff"
    logo = "images/ds-logo.svg"
    logoWidth = "150px"
  [params.fonts]
    body = "Maven Pro:400,700"
  [[params.social]]
    icon = "twitter"
    url = "https://twitter.com/datasketch"
  [[params.social]]
    icon = "facebook"
    url = "https://www.facebook.com/datasketch/"
  [[params.social]]
    icon = "instagram"
    url = "https://www.instagram.com/datasketch/"
  [params.footer]
    bg = "#2a2a2a"
    color = "#ffffff"
    text = "Este es un trabajo de periodismo de datos del equipo de [Datasketch](https://www.datasketch.co/). Revisa cómo creamos este especial en la [metodología](/lideres-sociales/metodologia). Todo el material en esta página es [CC-BY-SA](https://creativecommons.org/licenses/by-sa/4.0/). Si reusas o adaptas recursos de esta página, por favor vincula y referencia nuestro artículo o sitio web."
