---
title: "Contratistas De Leche en Colombia"
date: 2019-08-13T22:49:49-05:00
weight: 2
summary: "Desde compradores de tierras a familias desplazadas por el conflicto armado colombiano, hasta empresas del Programa de Alimentación Escolar que no cumplen con lo acordado, estos son los mayores contratistas de la leche en Colombia."
description: "Desde compradores de tierras a familias desplazadas por el conflicto armado colombiano, hasta empresas del Programa de Alimentación Escolar que no cumplen con lo acordado, estos son los mayores contratistas de la leche en Colombia."
images:
  - /la-via-lactea/images/article_2.png
---

Las empresas que más contratan con el Estado colombiano en relación con leche y productos lácteos desde el 2011 son La Recetta Soluciones Gastronómicas Integradas, Cooperativa Colanta LTDA, Lácteos Buenos Aires S.A.S y Nestlé de Colombia.

**Gráfica**

Así están compuestas las empresas que más contratan con el Estado en temas de leche en Colombia:

## Colanta

Colanta tiene un capital de más de 607 mil millones de pesos, tiene dentro de su junta directiva a Daniel Fernando Cuartas Tamayo, accionista de la Agropecuaria Carmen de Bolívar y de la Agropecuaria El Génesis (En liquidación), empresas involucradas en compras de tierras en Los Montes de María en Carmen de Bolívar.

**Red de personas que conforman la empresa**

[Ver](https://drive.google.com/drive/folders/1po-1rck4VZMYpZ96oE1PU_WOdadkGlDH) cuadro de composición de la empresa.

La Agropecuaria Carmen de Bolívar, [según](https://verdadabierta.com/agropecuaria-carmen-de-bolivar-no-actuo-de-buena-fe-tribunal-de-cartagena/) la Sala Civil Especializada en Restitución de Tierras del Tribunal de Cartagena, no actuó de buena fé en la compra de unas tierras hechas a campesinos en la región de Los Montes de María. La sentencia ordenó a la empresa la devolución de una finca de 24 hectáreas a sus dueños originales.

Este hecho es relatado por el portal Verdad Abierta, cuando relata que los dueños originales de estas tierras fueron desplazados por la violencia de la región pero “Cuando la familia se registró como víctima ante la Unidad de Restitución de Tierras y reclamó las 24 hectáreas narró que no habían podido volver a su tierra porque firmaron una promesa de venta en 2008 con Manuel Medina Muñetón, representante suplente de la Agropecuaria Carmen de Bolívar S.A., dedicada a la ganadería”.

Además el medio aclara que según la Superintendencia para la Protección, Restitución y Formalización de Tierras, esta Agropecuaria compró por lo menos 87 predios que suman 4.500 hectáreas. Da a conocer también que esta empresa es propiedad de Guillermo Gaviria, papá del ex-alcalde de Medellín Aníbal Gaviria.

En el caso de la persona que realizó la compra-venta, Manuel Medina, [El Tiempo](https://www.eltiempo.com/archivo/documento/MAM-4898840) encontró que 10 de sus compras aparecen sustentadas en escrituras falsas, ya que dentro de su actividad empresarial también fue representante legal de la Agropecuaria El Génesis, de la cuál Daniel Fernando Cuartas Tamayo también es accionista.

El Génesis [compró](https://www.scribd.com/doc/22831297/ventas-masivas-orip-el-carmen-de-bolivar) otros 70 predios que suman 4 mil hectáreas en el Carmen de Bolívar. Además, Medina Muñetón terminó [cediendo](https://lasillavacia.com/historia/asi-se-concentro-la-tierra-en-los-montes-de-maria-25534) sus títulos al Fideicomiso 1359, el mayor de los fideicomisos en la zona.

Todas estas empresas, según [La Silla Vacía](https://lasillavacia.com/historia/5346), fueron creadas en 2008, días o semanas antes de comprar la tierra para producirla.

Según la [Ley 160 de 1994](http://www.secretariasenado.gov.co/senado/basedoc/ley_0160_1994_pr001.html) (Ley de Baldíos) una persona o una sociedad no puede acumular tierras que originalmente son de la nación, como en este caso, ya que son tierras que se encuentran en proceso de solicitud de restitución de tierras, y suponen ser brindadas a campesinos de escasos recursos o dueños originales de las mismas.

Dentro de las investigaciones de [La Silla Vacía](https://lasillavacia.com/historia/asi-se-concentro-la-tierra-en-los-montes-de-maria-25534), se nombra que Cementos Argos S.A es uno de los mayores tenedores de tierra en Montes de María y que además tiene un proceso de reforestación en la zona por medio de la empresa Reforestadora del Caribe S.A cuyo proyecto expansivo ha tenido como detractores a los campesinos de la región. Su gerente Carlos Ignacio Gallego Palacio es a la vez miembro de la junta directiva de La Recetta Soluciones Gastronómicas Integradas, la empresa que más contrata en Colombia sobre temas de leche.

El informe [Justicia y paz. Tierras y territorios en las versiones de los paramilitares](https://issuu.com/centronacionalmemoriahistorica/docs/tierras-territorios/69) del Centro Nacional de Memoria Histórica, nombra a ciertos empresarios de la región de Montes de María que realizaron compras masivas de cerca de treinta mil hectáreas, entre ellos Manuel Medina Muñetón, Andrés Felipe, Daniel y Ricardo Arango Botero y Amauri Rafael Piniche pertenecientes a las empresas Cementos Argos SA.

Durante los últimos años, Colanta ha sido una de las empresas más reconocidas en producción y comercialización láctea en el país, y por lo tanto las contrataciones que ha realizado con el Estado colombiano reflejan las capacidades para suministrar productos lácteos a las distintas entidades estatales.

**Tabla de contratos de Colanta**

De los 70 contratos firmados por Colanta, 29 de ellos son firmados con el Instituto Nacional Penitenciario y Carcelario (INPEC) para el suministro de bebidas lácteas con el fin de ser vendidas dentro de los centros carcelarios a lo largo del país. Cuyos montos suman más de 1.600 millones de pesos.

De la misma manera, se han obtenido 24 contratos con la Agencia Logística de las Fuerzas Militares para dar cumplimiento a convenios administrativos entre la Agencia y el Instituto Colombiano de Bienestar Familiar, con el fin de suministrar productos alimenticios en restaurantes escolares. Estos montos suman más de 1.800 millones de pesos en total.

**Gráfica**

**Gráfica**

Colanta a pesar de que desde 2012 presentó unas caídas considerables con contratos estatales, en 2018 y lo que va de 2019 con tan solo 4 contratos a logrado recibir más de 3 mil millones de pesos por estos.

## La Recetta Soluciones Gastronómicas Integradas

La Recetta Soluciones Gastronómicas Integradas está compuesta principalmente por dos accionistas reconocidos en el país por la comercialización de leche y productos lácteos: Grupo Nutresa SA y Alpina Productos Alimenticios SA. Cuyo patrimonio es de más de 1.800 millones de pesos.

Ver documento de Patrimonio de la Recetta Soluciones Gastronómicas Integradas.

Casi todos los miembros de la junta directiva de la empresa se encuentran relacionados con otras empresas del sector productivo colombiano.

**Red**

[Ver](https://drive.google.com/drive/folders/1po-1rck4VZMYpZ96oE1PU_WOdadkGlDH) documento de composición de La Recetta Soluciones Gastronómicas Integradas.

De los 175 contratos celebrados por La Recetta con el Estado, 128 fueron firmados con el Instituto Nacional Penitenciario INPEC para el abastecimiento de los almacenes para el expendio de productos en los centros carcelarios por un total de 2.500 millones de pesos . Le siguen 34 contratos con la Agencia Logística de las Fuerzas Militares para el abastecimiento de las servitiendas de las fuerzas militares a lo largo del país por 551 millones de pesos en total.

**Tabla de contratos de la Recetta**

**Gráfica**

Vale anotar que el Grupo Nutresa SA una de las partes de la empresa, aportó en 2018, 30 millones de pesos a Óscar Darío Pérez Pineda, candidato a la Cámara de Representantes por el partido Centro Democrático, también financió 10 millones de pesos a Héctor Manuel Hoyos Meneses ex candidato a la alcaldía de Medellín en 2015 por el partido Polo Democrático Alternativo.

## Lácteos Buenos Aires S.A.S

Lácteos Buenos Aires S.A.S está compuesta por dos accionistas Luis Fernando Moreno Vélez y Alba Lucía Velásquez García. Cuyo patrimonio es de más de 3.600 millones de pesos.

[Ver](https://drive.google.com/drive/folders/1po-1rck4VZMYpZ96oE1PU_WOdadkGlDH) documento de composición y patrimonio de Lácteos Buenos Aires S.A.S

Lácteos Buenos Aires tiene 30 contratos con el Estado colombiano, todos ellos firmados con Metroparques de Antioquia para la compra de lácteos y cárnicos para la comercialización de bebidas en parques, que en total suman más de 300 millones de pesos.

**Tabla de contratos de Lácteos Buenos Aires**

**Gráfica**

## Nestlé

Nestlé es una empresa cuyo patrimonio sobrepasa los [162 mil millones de pesos](https://drive.google.com/drive/folders/1po-1rck4VZMYpZ96oE1PU_WOdadkGlDH) y cuyos contratos con el Estado colombiano en relación con leche desde 2011 (25 en total) se firmaron en su mayoría (11 contratos) con el Instituto Nacional de Bienestar Familiar para suministrar leches para menores de edad en situación de vulnerabilidad en todo el país, que suman más de 400 millones de pesos. Otros (10 contratos) son firmados con el Hospital La Victoria de Bogotá principalmente para el suministro de leches para pacientes recién nacidos y menores de edad de la entidad hospitalaria cuyo monto fue de 189 millones de pesos.

**Tabla de contratos de Nestlé**

**Gráfica**

## Los que reciben más por contratar

Los dineros por contratos en Colombia no son recibidos por quienes más contratan en el país. El contrato de mayor monto en temas lácteos se llevó a cabo entre el Fondo para el Financiamiento del Sector Agropecuario (FINAGRO) y el Ministerio de Agricultura para la implementación y adjudicación del incentivo a la Capitalización Rural- ICR y de la Línea Especial de Crédito del programa AIS-DRE y el Incentivo a la Capitalización Rural ICR para el sector Lácteo por 390 mil millones de pesos para llevar a cabo estas labores entre marzo de 2015 y marzo de 2016.

**Gráfica**

Uniagro S.A también contrató con la Agencia Logística de las Fuerzas Militares para la provisión de alimentos para abastecer servitiendas de las fuerzas militares, el contrato tuvo un monto de 52 mil millones de pesos ejecutados entre enero de 2014 y enero de 2015. El tercer gran monto en contratos lácteos se firmó entre Agrobursatil S.A y la Agencia Logística de las Fuerzas Militares por 44 mil millones de pesos ejecutados entre marzo de 2013 y marzo de 2014.

Los principales contratistas con el Estado colombiano firman acuerdos relacionados con la provisión de alimentos para ser vendidos en los mismas entidades a nivel nacional y territorial, casi ningún contrato se relaciona con provisión de alimentos para programas de asistencia a poblaciones vulnerables. 

Los programas de asistencia social casi siempre se relacionan con el soporte a programas de alimentación escolar a lo largo del país, que en los últimos años ha tenido gran impacto especialmente por los escándalos de corrupción y malos manejos administrativos que se dan por parte de los contratistas a estas iniciativas públicas.

## Programácion de Alimentación Escolar

La alimentación escolar, según su [plan de acción](https://www.mineducacion.gov.co/1621/articles-235135_archivo_pdf_lineamientos_tecnicos.pdf), es una estrategia que ha demostrado ser efectiva para promover la incorporación y permanencia de los estudiantes y de la comunidad en general en la vida de la escuela. Se creó mediante la Ley 1176 de 2007 con el objetivo de aumentar las tasas de matrículas en instituciones educativas públicas de Colombia, especialmente para el mejoramiento de la calidad educativa en el país.

En el caso de la leche, el Programa especifica que todos los días se les debe brindar al desayuno, refrigerio y almuerzo a niños de 4 a 17 años 100 cc de leche entera pasteurizada que debe ser brindada en los centros educativos a los menores de edad.

De los contratos del Programa de Alimentación Escolar relacionados con productos lácteos, los de mayor costo han sido celebrados con la misma entidad en un mismo periodo la Alcaldía del Municipio de Medellín, de 14 contratos 11 de ellos comenzaron a ejecutarse en febrero y abril de 2012 y finalizados entre marzo y julio de ese mismo año. Todos estos contratos suman en total más de 99 mil millones de pesos, y cuyas adiciones presupuestales son superiores a los 20 mil millones de pesos.

Estos contratos fueron firmados los meses inmediatos a la posesión como alcalde de Medellín de Aníbal Gaviria Correa en enero de 2012. Y los contratistas que recibieron mayor cantidad de dinero fueron Jaime Emilio Salazar Zuluaga, Consorcio Gómez & Zuluaga y Unión Temporal Generación Colombia 2012.

**Tabla contratos PAE**

La [adjudicación](https://docplayer.es/17133253-Vigencia-2013-secretaria-de-inclusion-social-y-familia-contraloria-general-de-medellin.html) del contrato se distribuyó de esta manera entre los distintos contratistas:

**Imagen**

A pesar de que en el documento de [Auditoría](https://docplayer.es/17133253-Vigencia-2013-secretaria-de-inclusion-social-y-familia-contraloria-general-de-medellin.html) del proyecto Nutrición Escolar Vaso de Leche y proyecto Nutrición Escolar Restaurantes Escolares de la Contraloría General de Medellín se habla de la licitación número 70004950 de 2012, los datos de SECOP registran que la licitación es la número 70004661 de 2012. Y que a pesar de que el total del monto de los contratos suma en el documento oficial más 37 mil millones de pesos, en la base de datos suma más de 78 mil millones de pesos, sin agregar las adiciones que se otorgaron en el contrato.

El documento resalta unas falencias en los procesos de supervisión e interventoría en el proceso de evaluación de estos contratos, ya que *“el equipo auditor evidenció incumplimientos sistemáticos y reiterativos por parte del contratista al componente técnico“ Suministro de Implementos de Aseo””*. Además se observan falencias en la supervisión de un contrato celebrado con Jaime Emilio Salazar Zuluaga, ya que el contrato tuvo unas adiciones cuyos documentos se firman 14 días después de realizarse dicha adición.

Según el [informe](http://revinut.udea.edu.co/index.php/ceo/article/download/6513/5971) de la Interventoría al programa de restaurantes escolares del municipio de Medellín realizado por la Universidad de Antioquia, Jaime Emilio Salazar Zuluaga “incumple con la calidad de los alimentos, la forma de los empaques y cambia los alimentos ofrecidos”.

Así es como se van tejiendo las redes de poder en la contratación de le leche en Colombia, desde empresas con gran capital, que ejecutan presupuestos para la provisión de alimentos en entidades públicas, hasta aquellas encargadas de brindarle los alimentos a los menores de edad en los principales colegios del país. Seguimos con la lupa puesta en los lecheros de Colombia.
